POST http://localhost:5147/api/v1/auth HTTP/1.1
Content-Type: application/json

{
  "email": "matthew.rc.simpson@hotmail.com",
  "password": "MasaPass123!"
}

###
POST http://localhost:5147/api/v1/auth HTTP/1.1
Content-Type: application/json

{
  "email": "matt.rc.simpson@gmail.com",
  "password": "SuperAdminPass2024!"
}