POST http://localhost:5147/api/v1/users HTTP/1.1
Content-Type: application/json

{
  "role": "Admin",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "SecretPassword123!",
  "phoneNumber": "1234567890",
  "addresses": [
    {
      "houseNumber": 123,
      "street": "Main Street",
      "postCode": "12345"
    }
  ]
}

# {
#   "Role": "Customer",
#   "FirstName": "Jane",
#   "LastName": "Doe",
#   "Email": "jane.doe@example.com",
#   "Password": "password123",
#   "PhoneNumber": "9876543210",
#   "Addresses": [
#     {
#       "HouseNumber": 456,
#       "Street": "Oak Avenue",
#       "PostCode": "67890"
#     }
#   ]
# }

###
POST http://localhost:5147/api/v1/products HTTP/1.1
Content-Type: application/json

{
  "productName": "Dummy Product",
  "description": "This is a dummy product description.",
  "image": ["dummy_image.jpg"],
  "price": "29.99",
  "stockQuantity": 100,
  "categoryId": "d46ae5af-8b81-414c-8d84-98c9c98d9d3e",
  "sizes": null,
  "colors": null
}


###
GET http://localhost:5147/api/v1/products HTTP/1.1
Content-Type: application/application/json

###
POST http://localhost:5147/api/v1/categorys HTTP/1.1
Content-Type: application/json

{
  "categoryName": "Dummy Category",
  "description": "This is a dummy category",
  "products": []
}

###
GET http://localhost:5147/api/v1/categorys HTTP/1.1
Content-Type: application/json

### ADMIN
GET http://localhost:5147/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMjE5MDkxMi1mZWZkLTQwMzItOTk3Yi02YWM5NTVmNmI0MzgiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwibmJmIjoxNzAzNjkxMjIwLCJleHAiOjE3MDM4NjQwMjAsImlhdCI6MTcwMzY5MTIyMCwiaXNzIjoiTWF0dGkiLCJhdWQiOiJGYWtlU3RvcmVBcHBVc2VycyJ9.xRbEdqmK-5gDPRzpFOYJWzFyvWM8fBRxdXCfsgmB4JU
### test CheckUser (non admin)
GET http://localhost:5147/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI1NzA4ZDBhYS0zYWQzLTRkNzktYmI5ZC0zN2JkZjgwZDg0MGYiLCJyb2xlIjoiQ3VzdG9tZXIiLCJlbWFpbCI6ImphbmUuZG9lQGV4YW1wbGUuY29tIiwibmJmIjoxNzAzNTkzMzEzLCJleHAiOjE3MDM3NjYxMTMsImlhdCI6MTcwMzU5MzMxMywiaXNzIjoiTWF0dGkiLCJhdWQiOiJGYWtlU3RvcmVBcHBVc2VycyJ9.eUkoObv6I5qqwoeP010lErlQADill6OMOSBqH6yJ62c
###
POST http://localhost:5147/api/v1/auth HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "SecretPassword123!"
}

###
POST http://localhost:5147/api/v1/auth HTTP/1.1
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "password": "password123"
}

### - customer own info
PATCH http://localhost:5147/api/v1/users/5708d0aa-3ad3-4d79-bb9d-37bdf80d840f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI1NzA4ZDBhYS0zYWQzLTRkNzktYmI5ZC0zN2JkZjgwZDg0MGYiLCJyb2xlIjoiQ3VzdG9tZXIiLCJlbWFpbCI6ImphbmUuZG9lQGV4YW1wbGUuY29tIiwibmJmIjoxNzAzNTkzMzEzLCJleHAiOjE3MDM3NjYxMTMsImlhdCI6MTcwMzU5MzMxMywiaXNzIjoiTWF0dGkiLCJhdWQiOiJGYWtlU3RvcmVBcHBVc2VycyJ9.eUkoObv6I5qqwoeP010lErlQADill6OMOSBqH6yJ62c

{
  "firstName": "Mary Jane",
  "lastName": "Watson",
  "email": "jane.doe@example.com",
  "phoneNumber": "9876543210",
  "addresses": [
    {
      "houseNumber": 456,
      "street": "Oak Avenue",
      "postCode": "67890"
    }
  ]
}
### - admin customer info
PATCH http://localhost:5147/api/v1/users/19120097-b9d2-48fc-a8b1-9a3725832f8f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2M2U5ODkwMi0xNTBmLTQ3MDQtYTMyZi1iMGM5ZjBjYWI0ZjYiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwibmJmIjoxNzAzNTgwMTkyLCJleHAiOjE3MDM3NTI5OTIsImlhdCI6MTcwMzU4MDE5MiwiaXNzIjoiTWF0dGkiLCJhdWQiOiJGYWtlU3RvcmVBcHBVc2VycyJ9.cgVY_2oh02b-XJeNrj6_m8qXU_di4U5yX_mJKo5yY_I

{
  "firstName": "Mary Jane",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "phoneNumber": "9876543210",
  "addresses": [
    {
      "houseNumber": 456,
      "street": "Oak Avenue",
      "postCode": "67890"
    }
  ]
}
###
PATCH http://localhost:5147/api/v1/users/d72e29f0-bda9-45be-aafa-af786834cd9d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI1NzA4ZDBhYS0zYWQzLTRkNzktYmI5ZC0zN2JkZjgwZDg0MGYiLCJyb2xlIjoiQ3VzdG9tZXIiLCJlbWFpbCI6ImphbmUuZG9lQGV4YW1wbGUuY29tIiwibmJmIjoxNzAzNTkzMzEzLCJleHAiOjE3MDM3NjYxMTMsImlhdCI6MTcwMzU5MzMxMywiaXNzIjoiTWF0dGkiLCJhdWQiOiJGYWtlU3RvcmVBcHBVc2VycyJ9.eUkoObv6I5qqwoeP010lErlQADill6OMOSBqH6yJ62c

{
  "firstName": "Stupid Johnny 2",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "phoneNumber": "1234567890",
  "addresses": [
    {
      "houseNumber": 123,
      "street": "Main Street",
      "postCode": "12345"
    }
  ]
}

###
DELETE http://localhost:5147/api/v1/users/19120097-b9d2-48fc-a8b1-9a3725832f8f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4Zjg5MTQ0Zi1mYzNkLTQ4MWMtYTJmMi1lZWExMjQ0Yjc0M2QiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwibmJmIjoxNzAzNjE0MDk4LCJleHAiOjE3MDM3ODY4OTgsImlhdCI6MTcwMzYxNDA5OCwiaXNzIjoiTWF0dGkiLCJhdWQiOiJGYWtlU3RvcmVBcHBVc2VycyJ9.LDqb94Itg_3gBXEByUZ2su9glOakDUiDUd6fjAjhMH8